# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃ 🌌 extraplanares.yml – Ritual de invocação dimensional                     ┃
# ┃ 📜 Executa rituais aprovados na branch ExtraPlanares                      ┃
# ┃ 🔒 Registra no README e comita com identidade ritualística                ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
name: Ritual ExtraPlanares

on:
  workflow_dispatch:
  push:
    branches: [ExtraPlanares]
    paths:
      - extraplanar/*.dart
      - .github/workflows/extraplanares.yml

permissions:
  contents: write

jobs:
  invocacao:
    name: Invocacao Dimensional
    runs-on: ubuntu-latest
    steps:
      - name: Checkout da branch
        uses: actions/checkout@v4
        with:
          ref: ExtraPlanares

      - name: Instalar Dart
        uses: dart-lang/setup-dart@v1

      - name: Detectar e invocar ultimo ritual
        id: ritual
        run: |
          ultimo=$(find extraplanar -maxdepth 1 -type f -name '*.dart' | sort | tail -n 1)
          nome=$(basename "$ultimo" .dart)
          echo "Invocando: $nome"
          dart run "$ultimo" || echo "// falha ignorada"
          echo "$nome" > .ritual_atual.txt
          echo "ritual_nome=$nome" >> $GITHUB_OUTPUT

      - name: Registrar no README.md
        run: |
          nome=$(cat .ritual_atual.txt)
          # Garante seção "## Rituais" existe
          grep "## Rituais" README.md || echo -e "\n## Rituais" >> README.md
          # Adiciona apenas se não existir
          grep "^- $nome" README.md || echo "- $nome" >> README.md

      - name: Commit automatico
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "🔮 Ritual extraplanar invocado: ${{ steps.ritual.outputs.ritual_nome }}"
          branch: ExtraPlanares
          file_pattern: README.md
          commit_user_name: ritual-bot
          commit_user_email: ritual@bot.com
